apiVersion: apps/v1
kind: Deployment
metadata:
  name: $CI_PROJECT_NAME
spec:
  replicas: 1
  progressDeadlineSeconds: 120
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      name: $CI_PROJECT_NAME
  template:
    metadata:
      name: $CI_PROJECT_NAME
      labels:
        date: "$DATE"
        name: $CI_PROJECT_NAME
    spec:
      containers:
        - name: $CI_PROJECT_NAME
          image: gcr.io/vero-2020/$CI_PROJECT_NAME:$IMAGE_TAG
          imagePullPolicy: Always
          command:
            - /bin/sh
            - -c
          args:
            - python manage.py wait_for_db && python manage.py migrate && python manage.py runserver 0.0.0.0:8000
          resources:
            limits:
              cpu: 200m
          envFrom:
            - configMapRef:
                name: $CI_PROJECT_NAME
            - secretRef:
                name: $CI_PROJECT_NAME
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: $CI_PROJECT_NAME
  name: $CI_PROJECT_NAME
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8000
  selector:
    name: $CI_PROJECT_NAME
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-origin: 'http(s)?://(www\.)?(dev.withvero.com|withvero.com)$'
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
  #    nginx.ingress.kubernetes.io/rewrite-target: /
  name: $CI_PROJECT_NAME
spec:
  rules:
    - host: $HOST
      http:
        paths:
          - backend:
              serviceName: $CI_PROJECT_NAME
              servicePort: 80
            path: /
  tls:
    - hosts:
        - $HOST
      secretName: withvero-com
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: $CI_PROJECT_NAME
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: $CI_PROJECT_NAME
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 75
