# Generated by Django 2.1.10 on 2019-08-07 17:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190807_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='debt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.DecimalValidator], verbose_name='debt'),
        ),
        migrations.AddField(
            model_name='user',
            name='have_accident_cover',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ("Don't know", "Don't know")], max_length=50, null=True, verbose_name='accident'),
        ),
        migrations.AddField(
            model_name='user',
            name='have_auto_cover',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ("Don't know", "Don't know")], max_length=50, null=True, verbose_name='auto'),
        ),
        migrations.AddField(
            model_name='user',
            name='have_criticalillness_cover',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ("Don't know", "Don't know")], max_length=50, null=True, verbose_name='critical illness'),
        ),
        migrations.AddField(
            model_name='user',
            name='have_dental_cover',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ("Don't know", "Don't know")], max_length=50, null=True, verbose_name='dental'),
        ),
        migrations.AddField(
            model_name='user',
            name='have_health_cover',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ("Don't know", "Don't know")], max_length=50, null=True, verbose_name='health'),
        ),
        migrations.AddField(
            model_name='user',
            name='have_homeowner_cover',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ("Don't know", "Don't know")], max_length=50, null=True, verbose_name='homeowner'),
        ),
        migrations.AddField(
            model_name='user',
            name='have_life_cover',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ("Don't know", "Don't know")], max_length=50, null=True, verbose_name='life'),
        ),
        migrations.AddField(
            model_name='user',
            name='have_longtermdisability_cover',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ("Don't know", "Don't know")], max_length=50, null=True, verbose_name='long term disability'),
        ),
        migrations.AddField(
            model_name='user',
            name='have_renters_cover',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ("Don't know", "Don't know")], max_length=50, null=True, verbose_name='renters'),
        ),
        migrations.AddField(
            model_name='user',
            name='have_shorttermdisability_cover',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ("Don't know", "Don't know")], max_length=50, null=True, verbose_name='short term disability'),
        ),
        migrations.AddField(
            model_name='user',
            name='have_vision_cover',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ("Don't know", "Don't know")], max_length=50, null=True, verbose_name='dental'),
        ),
        migrations.AddField(
            model_name='user',
            name='own_pet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='own_rent_house',
            field=models.CharField(blank=True, choices=[('Rent', 'Rent'), ('Own', 'Own'), ('None', 'None')], max_length=50, null=True, verbose_name='house'),
        ),
        migrations.AddField(
            model_name='user',
            name='own_vehicle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='saving',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.DecimalValidator], verbose_name='saving'),
        ),
    ]
