# Generated by Django 2.1.11 on 2019-08-08 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190807_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='content_digital',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='score',
            name='content_income',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='score',
            name='content_liability',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='score',
            name='content_medical',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='score',
            name='content_overall',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='score',
            name='content_stuff',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='debt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='debt'),
        ),
        migrations.AlterField(
            model_name='user',
            name='education',
            field=models.CharField(blank=True, choices=[('High school', 'High school'), ('College', 'College'), ('University', 'University')], default='', max_length=50, verbose_name='education'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='email address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='employment',
            field=models.CharField(blank=True, choices=[('Student', 'Student'), ('Full time', 'Full time'), ('Part time', 'Part time')], default='', max_length=50, verbose_name='employment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='first name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='have_accident_cover',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ("Don't know", "Don't know")], default='', max_length=50, verbose_name='accident'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='have_auto_cover',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ("Don't know", "Don't know")], default='', max_length=50, verbose_name='auto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='have_criticalillness_cover',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ("Don't know", "Don't know")], default='', max_length=50, verbose_name='critical illness'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='have_dental_cover',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ("Don't know", "Don't know")], default='', max_length=50, verbose_name='dental'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='have_health_cover',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ("Don't know", "Don't know")], default='', max_length=50, verbose_name='health'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='have_homeowner_cover',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ("Don't know", "Don't know")], default='', max_length=50, verbose_name='homeowner'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='have_life_cover',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ("Don't know", "Don't know")], default='', max_length=50, verbose_name='life'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='have_longtermdisability_cover',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ("Don't know", "Don't know")], default='', max_length=50, verbose_name='long term disability'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='have_renters_cover',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ("Don't know", "Don't know")], default='', max_length=50, verbose_name='renters'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='have_shorttermdisability_cover',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ("Don't know", "Don't know")], default='', max_length=50, verbose_name='short term disability'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='have_vision_cover',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ("Don't know", "Don't know")], default='', max_length=50, verbose_name='dental'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='income'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='last name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='own_rent_house',
            field=models.CharField(blank=True, choices=[('Rent', 'Rent'), ('Own', 'Own'), ('None', 'None')], default='', max_length=50, verbose_name='house'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='saving',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='saving'),
        ),
    ]
