# Generated by Django 2.1.11 on 2019-08-08 16:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190808_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='zipcode',
            field=models.CharField(blank=True, default='', max_length=5, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='zipcode'),
            preserve_default=False,
        ),
    ]
