# Generated by Django 2.1.11 on 2019-08-10 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190808_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='own_rent_house',
        ),
    ]
