# Generated by Django 2.1.11 on 2019-08-10 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_user_own_rent_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='own_rent_house',
            field=models.BooleanField(default=False),
        ),
    ]
