# Generated by Django 2.1.11 on 2019-08-13 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20190811_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='education',
            field=models.CharField(blank=True, choices=[('Associate degree', 'Associate degree'), ("Bachelor's degree", "Bachelor's degree"), ("Master's degree", "Master's degree"), ('Doctoral degree', 'Doctoral degree')], max_length=50, verbose_name='education'),
        ),
        migrations.AlterField(
            model_name='user',
            name='employment',
            field=models.CharField(blank=True, choices=[('Employed', 'Employed'), ('Unemployed', 'Unemployed'), ('Contractor', 'Contractor'), ('Student', 'Student')], max_length=50, verbose_name='employment'),
        ),
    ]
