# Generated by Django 2.1.11 on 2019-08-13 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20190813_0041'),
        ('core', '0011_auto_20190808_2052'),
    ]

    operations = [
    ]
